#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
PD_DIR="$(cd -- "${SCRIPT_DIR}/../.." && pwd)"
RUN_DIR="${RUN_DIR:-${PD_DIR}/runs-host/new-method/1p5d-c384}"
mkdir -p "${RUN_DIR}"
"${PD_ENV_BIN:-/homes/siqic/anaconda3/envs/pd/bin}/python" \
  "${SCRIPT_DIR}/../tools/check_environments.py" --expect modified \
  --output "${RUN_DIR}/environment.json"

env \
  PD_ENV_BIN="${PD_ENV_BIN:-/homes/siqic/anaconda3/envs/pd/bin}" \
  RUN_DIR="${RUN_DIR}" \
  PREFILL_GPU="${PREFILL_GPU:-0}" \
  DECODE_GPUS="${DECODE_GPUS:-1 2 3 4 5}" \
  DECODE_PORTS="${DECODE_PORTS:-27301 27302 27303 27304 27305}" \
  PREFILL_PORT="${PREFILL_PORT:-27300}" ROUTER_PORT="${ROUTER_PORT:-27310}" \
  ROUTER_PROMETHEUS_PORT="${ROUTER_PROMETHEUS_PORT:-27320}" \
  BOOTSTRAP_PORT="${BOOTSTRAP_PORT:-28300}" \
  SEARCH_GPU="${SEARCH_GPU:-6}" SEARCH_PORT="${SEARCH_PORT:-8730}" \
  MATH_RATIO="${MATH_RATIO:-0.5}" DISPATCH_POLICY="${DISPATCH_POLICY:-fixed}" \
  SCHEDULE_FILE="${SCHEDULE_FILE:-${PD_DIR}/configs/workloads/fixed_random_s2026_n4096.json}" \
  SEED="${SEED:-2026}" REQUESTS="${REQUESTS:-4096}" \
  MAX_INFLIGHT="${MAX_INFLIGHT:-384}" \
  PD_LATE_BINDING="${PD_LATE_BINDING:-1}" \
  SGLANG_PD_LATE_BIND_POLL_INTERVAL_S="${LATE_BIND_POLL_INTERVAL_SECONDS:-0.02}" \
  SGLANG_PD_LATE_BIND_MAX_PREFILL_INFLIGHT="${MAX_PREFILL_INFLIGHT:-64}" \
  SGLANG_PD_LATE_BIND_ACCEPT_TIMEOUT_S="${P_ACCEPT_TIMEOUT_SECONDS:-30}" \
  SGLANG_PD_LATE_BIND_QUEUE_TIMEOUT_S="${P_QUEUE_TIMEOUT_SECONDS:-3600}" \
  PD_LATE_BIND_READY_TIMEOUT_S="${P_READY_TIMEOUT_SECONDS:-600}" \
  SGLANG_PD_LATE_BIND_NEW_AGING_S="${NEW_AGING_SECONDS:-10}" \
  CLOSED_LOOP_WARMUP_MIN_SECONDS="${WARMUP_SECONDS:-300}" \
  CLOSED_LOOP_WARMUP_COMPLETIONS=0 CLOSED_LOOP_RECENT_SECONDS=120 \
  CLOSED_LOOP_MAX_WARMUP_SECONDS="${MAX_WARMUP_SECONDS:-420}" \
  CLOSED_LOOP_MEASUREMENT_SECONDS="${MEASURE_SECONDS:-1200}" \
  PD_MAX_TRANSFER_INFLIGHT=8 \
  SGLANG_AGENTIC_KV_FAST_TOOL_THRESHOLD="${FAST_TOOL_THRESHOLD_SECONDS:-2}" \
  SGLANG_AGENTIC_KV_DIRECT_HANDSHAKE_TIMEOUT="${DIRECT_WAIT_SECONDS:-2}" \
  SGLANG_AGENTIC_KV_EARLY_CLAIM=1 \
  SGLANG_AGENTIC_KV_EARLY_CLAIM_POST_TIMEOUT="${EARLY_CLAIM_POST_TIMEOUT_SECONDS:-2}" \
  SGLANG_AGENTIC_KV_DIRECT_D_HBM_HIGH_WATERMARK="${D_HBM_HIGH_WATERMARK:-0.85}" \
  SGLANG_AGENTIC_KV_DIRECT_MANIFEST_POLL_INTERVAL=0.10 \
  SGLANG_AGENTIC_KV_ADMISSION_SCAN_LIMIT="${ADMISSION_SCAN_LIMIT:-32}" \
  SGLANG_AGENTIC_KV_ADMISSION_BATCH="${ADMISSION_BATCH:-1}" \
  SGLANG_AGENTIC_KV_SELECTED_IO_CAP="${SELECTED_IO_CAP:-4}" \
  SGLANG_AGENTIC_KV_SLOW_AGING_SECONDS="${SLOW_AGING_SECONDS:-2}" \
  SGLANG_AGENTIC_KV_NEW_AGING_SECONDS="${NEW_AGING_SECONDS:-10}" \
  SGLANG_AGENTIC_KV_P_H2D_MAX_INFLIGHT="${P_H2D_MAX_INFLIGHT:-4}" \
  SGLANG_PD_P_READY_BACKPRESSURE_MODE="${P_READY_BACKPRESSURE_MODE:-continuous}" \
  SGLANG_PD_P_READY_HBM_HIGH_WATERMARK="${P_READY_HBM_HIGH_WATERMARK:-0.85}" \
  SGLANG_PD_P_READY_MAX_INFLIGHT="${P_READY_MAX_INFLIGHT:-0}" \
  SGLANG_AGENTIC_KV_STAGING_SLOT_MIB="${STAGING_SLOT_MIB:-256}" \
  MC_TCP_ENABLE_CONNECTION_POOL=1 SERVICE_STARTUP_TIMEOUT_SECONDS=300 \
  PD_SERVICE_GRACEFUL_SHUTDOWN_SECONDS="${PD_SERVICE_GRACEFUL_SHUTDOWN_SECONDS:-10}" \
  PD_SERVICE_KILL_WAIT_SECONDS="${PD_SERVICE_KILL_WAIT_SECONDS:-5}" \
  PD_AUX_SERVICE_GRACEFUL_SHUTDOWN_SECONDS="${PD_AUX_SERVICE_GRACEFUL_SHUTDOWN_SECONDS:-5}" \
  bash "${SCRIPT_DIR}/internal/run_agentic_pipeline.sh"
