#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
PD_DIR="$(cd -- "${SCRIPT_DIR}/../.." && pwd)"
export PD_ENV_BIN=/homes/siqic/anaconda3/envs/pd/bin
export PATH="${PD_ENV_BIN}:${PATH}"
export PYTHONPATH="/homes/siqic/sglang-h100-integration/python:${PD_DIR}:/homes/siqic/slime:${PYTHONPATH:-}"
export MODEL_PATH=/homes/siqic/Qwen3-32B
export PD_DATA_ROOT=/homes/siqic/data
export QA_DATA=/homes/siqic/data/browsecomp/bc_train.jsonl
export WORKLOAD_CONFIG="${PD_DIR}/configs/experiments/browsecomp_source_order.yaml"
export SEARCH_PORT=8750
export SEARCH_SERVER_EMBEDDING_CACHE="${PD_DIR}/data/browsecomp/artifacts/search/corpus_embeddings.pkl"
export MAX_INFLIGHT=256 WARMUP_SECONDS=300 MAX_WARMUP_SECONDS=420 MEASURE_SECONDS=1200
export BOOTSTRAP_PORT=29340 BOOTSTRAP_PORTS=29340
export PREFILL_PORTS=31340 DECODE_PORTS='31341 31342 31343'
export ROUTER_PORT=31350 ROUTER_PROMETHEUS_PORT=31360
export MEM_FRACTION_STATIC=0.80 DECODE_MEM_FRACTION_STATICS='0.80 0.80 0.60'
export MAX_EXISTING_GPU_MEMORY_MB=1024
export FAST_TOOL_THRESHOLD_SECONDS=1 DIRECT_WAIT_SECONDS=1
export SGLANG_AGENTIC_KV_SLOW_CONGESTION_RECOMPUTE=true
export SGLANG_AGENTIC_KV_SLOW_CONGESTION_HIGH="${SGLANG_AGENTIC_KV_SLOW_CONGESTION_HIGH:-8}"
export SGLANG_AGENTIC_KV_SLOW_CONGESTION_LOW="${SGLANG_AGENTIC_KV_SLOW_CONGESTION_LOW:-2}"
export SGLANG_AGENTIC_KV_FAST_DIRECT_FAILURE_RECOMPUTE=false
export SGLANG_AGENTIC_KV_FORCE_SLOW_PATH=false SGLANG_AGENTIC_KV_DISABLE_D2P_REUSE=false
export SGLANG_PD_ABLATION_P2D_PREBIND=false SGLANG_PD_ABLATION_RANDOM_ROUTING=false
export D_TARGET_KV_FRACTION=1.0 P2D_SPILL_DELAY_SECONDS=0.5
export SGLANG_AGENTIC_KV_REGISTERED_EXTENT_DMA=1 SGLANG_AGENTIC_KV_REGISTER_EAGER_ARENA=1
export SGLANG_AGENTIC_KV_REGISTER_STARTUP_BARRIER=1 SGLANG_AGENTIC_KV_REGISTER_CACHE_GIB=640
export SGLANG_AGENTIC_KV_REGISTER_WINDOW_GIB=8
export SGLANG_AGENTIC_KV_SHARED_HOST_ARENA_GIB=128
export SGLANG_AGENTIC_KV_D2H_INFLIGHT=2 P_H2D_MAX_INFLIGHT=2
export SGLANG_AGENTIC_KV_P2D_D2H_WORKERS=2 SGLANG_AGENTIC_KV_P2D_H2D_WORKERS=2
export SGLANG_AGENTIC_KV_D2H_CHUNK_TOKENS=4096 SGLANG_AGENTIC_KV_P_H2D_CHUNK_TOKENS=4096
export SGLANG_AGENTIC_KV_P2D_D2H_CHUNK_TOKENS=4096 SGLANG_AGENTIC_KV_P2D_H2D_CHUNK_TOKENS=4096
export RUN_DIR="${RUN_DIR:-${PD_DIR}/runs-host/current/qwen3-32b-tp2-browsecomp-c256-w300-m1200/current-method-recheck-20260910-r1}"
exec bash "${SCRIPT_DIR}/run_qwen3_32b_tp2_browsecomp_2p6d.sh"
