#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
PD_DIR="$(cd -- "${SCRIPT_DIR}/../.." && pwd)"
if [[ -n "${EXPERIMENT_CONFIG:-}" ]]; then
  # shellcheck source=internal/apply_experiment_profile.sh
  source "${SCRIPT_DIR}/internal/apply_experiment_profile.sh"
  apply_experiment_profile \
    "${EXPERIMENT_CONFIG}" \
    "${SCRIPT_DIR}/../tools/load_experiment_profile.py" \
    "${PD_ENV_BIN:-/homes/siqic/anaconda3/envs/pd/bin}/python"
fi
RUN_DIR="${RUN_DIR:-${PD_DIR}/runs-host/new-method/4p4d-numa-c512}"
mkdir -p "${RUN_DIR}"
"${PD_ENV_BIN:-/homes/siqic/anaconda3/envs/pd/bin}/python" \
  "${SCRIPT_DIR}/../tools/check_environments.py" --expect modified \
  --output "${RUN_DIR}/environment.json"

env \
  PD_ENV_BIN="${PD_ENV_BIN:-/homes/siqic/anaconda3/envs/pd/bin}" RUN_DIR="${RUN_DIR}" \
  PREFILL_GPU=0 PREFILL_GPUS="${PREFILL_GPUS:-0 2 4 6}" \
  PREFILL_PORT=27300 PREFILL_PORTS="${PREFILL_PORTS:-27300 27320 27400 27420}" \
  BOOTSTRAP_PORT=28300 BOOTSTRAP_PORTS="${BOOTSTRAP_PORTS:-28300 28320 28400 28420}" \
  DECODE_GPUS="${DECODE_GPUS:-1 3 5 7}" \
  DECODE_PORTS="${DECODE_PORTS:-27301 27321 27401 27421}" \
  DECODE_MEM_FRACTION_STATICS="${DECODE_MEM_FRACTION_STATICS:-0.85 0.85 0.85 0.74}" \
  ROUTER_PORT="${ROUTER_PORT:-27510}" ROUTER_PROMETHEUS_PORT="${ROUTER_PROMETHEUS_PORT:-27520}" \
  SEARCH_GPU="${SEARCH_GPU:-7}" SEARCH_PORT="${SEARCH_PORT:-8750}" \
  MATH_RATIO="${MATH_RATIO:-0.5}" DISPATCH_POLICY=fixed \
  PD_INFERENCE_RETURN_LOGPROB=false \
  SCHEDULE_FILE="${SCHEDULE_FILE:-${PD_DIR}/configs/workloads/fixed_random_s2026_n4096.json}" \
  SEED="${SEED:-2026}" REQUESTS="${REQUESTS:-4096}" MAX_INFLIGHT="${MAX_INFLIGHT:-512}" \
  PD_LATE_BINDING=1 PD_LATE_BIND_NUMA_DOMAINS=1 \
  SGLANG_PD_LATE_BIND_DYNAMIC_PREFILL_DOMAINS=1 \
  SGLANG_PD_LATE_BIND_GLOBAL_DECODE=1 \
  SGLANG_PD_LATE_BIND_POLL_INTERVAL_S="${LATE_BIND_POLL_INTERVAL_SECONDS:-0.02}" \
  SGLANG_PD_LATE_BIND_MAX_PREFILL_INFLIGHT="${MAX_PREFILL_INFLIGHT:-12}" \
  SGLANG_PD_LATE_BIND_TARGET_KV_FRACTION="${D_TARGET_KV_FRACTION:-1.0}" \
  SGLANG_PD_LATE_BIND_ACCEPT_TIMEOUT_S="${P_ACCEPT_TIMEOUT_SECONDS:-30}" \
  SGLANG_PD_LATE_BIND_QUEUE_TIMEOUT_S="${P_QUEUE_TIMEOUT_SECONDS:-3600}" \
  PD_LATE_BIND_READY_TIMEOUT_S="${P_READY_TIMEOUT_SECONDS:-600}" \
  CLOSED_LOOP_WARMUP_MIN_SECONDS="${WARMUP_SECONDS:-300}" CLOSED_LOOP_WARMUP_COMPLETIONS=0 \
  CLOSED_LOOP_RECENT_SECONDS=120 CLOSED_LOOP_MAX_WARMUP_SECONDS="${MAX_WARMUP_SECONDS:-420}" \
  CLOSED_LOOP_MEASUREMENT_SECONDS="${MEASURE_SECONDS:-1200}" \
  PD_MAX_TRANSFER_INFLIGHT=8 \
  SGLANG_PREFILL_TRANSFER_CONSUMERS="${P_TO_D_CONSUMERS:-24}" \
  SGLANG_PREFILL_TRANSFER_PROGRESS_INTERVAL_SECONDS="${P_TO_D_POLL_INTERVAL_SECONDS:-0.015}" \
  PD_PREFILL_HICACHE_SIZE_GB=64 PD_DECODE_HICACHE_SIZE_GB=56 \
  SGLANG_AGENTIC_KV_SHARED_HOST_ARENA_GIB="${D2P_HOST_ARENA_GIB_PER_P:-256}" \
  SGLANG_AGENTIC_KV_P2D_HOST_ARENA_BACKEND="${SGLANG_AGENTIC_KV_P2D_HOST_ARENA_BACKEND:-memfd}" \
  SGLANG_AGENTIC_KV_P2D_HOST_STAGING="${P2D_HOST_STAGING:-true}" \
  SGLANG_AGENTIC_KV_P2D_SHARED_HOST_ARENA_GIB="${P2D_HOST_ARENA_GIB_PER_P:-64}" \
  SGLANG_AGENTIC_KV_P2D_SPILL_DELAY_SECONDS="${P2D_SPILL_DELAY_SECONDS:-0.5}" \
  SGLANG_AGENTIC_KV_HOST_CAPACITY_WAIT_TIMEOUT_SECONDS="${HOST_CAPACITY_WAIT_TIMEOUT_SECONDS:-0}" \
  SGLANG_AGENTIC_KV_FAST_TOOL_THRESHOLD="${FAST_TOOL_THRESHOLD_SECONDS:-2}" \
  SGLANG_AGENTIC_KV_DIRECT_HANDSHAKE_TIMEOUT="${DIRECT_WAIT_SECONDS:-2}" \
  SGLANG_AGENTIC_KV_EARLY_CLAIM=1 \
  SGLANG_AGENTIC_KV_ADMISSION_SCAN_LIMIT=64 SGLANG_AGENTIC_KV_ADMISSION_BATCH=8 \
  SGLANG_AGENTIC_KV_DIRECT_IO_CAP="${DIRECT_IO_CAP:-8}" \
  SGLANG_AGENTIC_KV_SELECTED_IO_CAP="${SELECTED_IO_CAP:-4}" \
  SGLANG_AGENTIC_KV_P_H2D_MAX_INFLIGHT="${P_H2D_MAX_INFLIGHT:-4}" \
  SGLANG_AGENTIC_KV_D2H_ACTIVE_SNAPSHOTS="${D2H_ACTIVE_SNAPSHOTS:-8}" \
  SGLANG_AGENTIC_KV_D2H_PROGRESS_BUDGET="${D2H_PROGRESS_BUDGET:-8}" \
  SGLANG_AGENTIC_KV_D2H_BOUNCE_DEPTH="${D2H_BOUNCE_DEPTH:-2}" \
  SGLANG_AGENTIC_KV_D2H_HOST_COPY_WORKERS="${D2H_HOST_COPY_WORKERS:-4}" \
  SGLANG_AGENTIC_KV_P_H2D_BOUNCE_DEPTH="${P_H2D_BOUNCE_DEPTH:-2}" \
  SGLANG_AGENTIC_KV_P_H2D_HOST_COPY_WORKERS="${P_H2D_HOST_COPY_WORKERS:-2}" \
  SGLANG_AGENTIC_KV_P2D_D2H_HOST_COPY_WORKERS="${P2D_D2H_HOST_COPY_WORKERS:-4}" \
  SGLANG_AGENTIC_KV_P2D_H2D_HOST_COPY_WORKERS="${P2D_H2D_HOST_COPY_WORKERS:-2}" \
  SGLANG_AGENTIC_KV_LEDGER_CACHE_SECONDS=0.20 \
  SGLANG_AGENTIC_KV_P_CONTROL_POLL_SECONDS=0.02 \
  SGLANG_AGENTIC_KV_D_CONTROL_POLL_SECONDS=0.05 \
  SGLANG_DECODE_IO_METADATA_BATCH="${P_TO_D_METADATA_BATCH:-8}" \
  SGLANG_AGENTIC_KV_RELAY_ENABLED="${RELAY_ENABLED:-false}" \
  SGLANG_AGENTIC_KV_ISOLATE_RELAY_PROGRESS=1 \
  SGLANG_PD_P_READY_BACKPRESSURE_MODE="${P_READY_BACKPRESSURE_MODE:-disabled}" \
  SGLANG_PD_P_READY_MAX_INFLIGHT=0 \
  SGLANG_PD_P_READY_REQUEST_CAP="${P_READY_REQUEST_CAP:-0}" \
  SGLANG_PD_P_READY_TOKEN_CAP_FRACTION="${P_READY_TOKEN_CAP_FRACTION:-0.25}" \
  SGLANG_PD_P_READY_HBM_HIGH_WATERMARK="${P_READY_HBM_HIGH_WATERMARK:-0.85}" \
  SGLANG_AGENTIC_KV_STAGING_SLOT_MIB=128 \
  MC_TCP_ENABLE_CONNECTION_POOL=1 SERVICE_STARTUP_TIMEOUT_SECONDS=300 \
  bash "${SCRIPT_DIR}/internal/run_agentic_pipeline.sh"
